
### Successfully create a new Auction
POST http://localhost:8082/auctions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

{
  "productName": "product1",
  "minimumBid": 100,
  "sellerId": 1
}

### Create new Auction Validation
POST http://localhost:8082/auctions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

{

}


### Create new Auction Validation
POST http://localhost:8082/auctions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

{
  "productName": "",
  "minimumBid": 0,
  "sellerId": 1
}

### Successfully create a new Bid
POST http://localhost:8082/auctions/bid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

{
  "auctionId": 1,
  "amount": 101,
  "buyerId": 2
}

### Successfully close an auction
POST http://localhost:8082/auctions/1/close
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

### new Bid Validation
POST http://localhost:8082/auctions/bid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

{

}

### new Bid Validation
POST http://localhost:8082/auctions/bid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A

{
  "auctionId": 1,
  "amount": 0,
  "buyerId": 2
}


### close auction validation
POST http://localhost:8082/auctions/10000/close
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlzcyI6ImJpZGJhbmtlciIsImlhdCI6MTcxNzQyNTA1MSwiZXhwIjoxNzE3NDI4NjUxfQ.OkZlFCrbpKipGorAV64C9SIzFwTh8esA71Vq8rd4Zjy6oMrMBMShdwxl9Vw8jg2ov6hX5IhABl9uG3Sb00XpLk_F3IlAEomYVemjloE7-L5bkcSCA8vpvlK99cos6d-Vt7yBfH_Sx3aIKWL1sx3EAuuG1n1vl15kbbKMmIQznkVhhsvz85K7BfJFHCXsLjcBIn04XhrMNpGoQjmsf_7BKf2KHjCAzQIu1YmOG6tYTsvy5_PlCzCWcBCCcS0Vyl9W4u41u0PRJZgGnC8fn3ex7M4hb1lzKUFqM2JhK-gfjO0-EUcwBkwuKKo-V3fbyz9QQAUlFI2Z-3YuaUccbO5W1A
