
### Successfully create a new User
POST http://localhost:8081/users/register
Content-Type: application/json

{
  "username": "user1",
  "email": "user1@example.com",
  "password": "germany"
}


### User Login
POST http://localhost:8081/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "germany"

}

### Create new User Validation
POST http://localhost:8081/users/register
Content-Type: application/json

{

}


### Create new User Validation
POST http://localhost:8081/users/register
Content-Type: application/json

{
  "username": "n",
  "email": "g",
  "password": "n"
}

###