spring:
  application:
    name: auctions
  r2dbc:
    url: r2dbc:h2:mem:///auctions;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: r2dbc:h2:file:////Users/<user>/code/BidBanker/auctions;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  liquibase:
    enabled: true
    url: jdbc:h2:mem:auctions;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    url: jdbc:h2:file:///Users/<user>/code/BidBanker/auctions;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    change-log: classpath:db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
server:
  port: 8082

jwt:
  public-key:  |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp50k7E9Ipi218MtJhk7A
    BHzYNqFpx9mpsye45ED9umWmTCYBLZzcGfoZY93w593vw/h8afoeWuywIjHJd931
    pD549CnxsK+a9pzCp8/8XO1A5+Ftwk1+ZejHTUYmQrt8aE4BiEyIJyZjwi+/4K7v
    UzZDz8MC662oHTpW7WuW7EeUP8mXVG5w4Ual2PaMulApc6qfIB6mhg5XiDuQyIpW
    g8ezMX2dFhCHHZS6xUa2PPpmeGfLvIWtFWbkkKjT+v2NFA2JIJNSCfYQmn4420p8
    XklRHJsJHRA0BpsoR6jxz8whF2ZcExSlSeeKHzY3cy+cFT3iMJc7KVjW459Hboqh
    BwIDAQAB
    -----END PUBLIC KEY-----
  issuer: bidbanker
  expiration: 3600000 # 1 hour in milliseconds