name: Users Service CI

on:
  push:
    paths:
      - 'users-service/**'
      - 'common/**'
  pull_request:
    paths:
      - 'users-service/**'
      - 'common/**'

jobs:
  build:
    name: Build and Test Users Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Test Users Service
        run: ./gradlew :common:build :users-service:build :common:test :users-service:test --no-daemon